### ISSUE TITLE
httpoison error when using sandbox API

### ISSUE THREAD

**Issue by adamkittelson** [dnsimple/dnsimple-elixir#127]
When hitting the sandbox API I get the following error. I'm guessing you're using a self-signed cert or something with the sandbox API? I do not get the error when hitting the production API.
```
** (HTTPoison.Error) {:tls_alert, 'unknown ca'}
    (httpoison) lib/httpoison.ex:128: HTTPoison.request!/5
    (dnsimple) lib/dnsimple.ex:122: Dnsimple.Client.execute/5
    (dnsimple) lib/dnsimple/identity.ex:32: Dnsimple.Identity.whoami/2
```

The error can be worked around by adding the following option to a call:
`ssl: [{:versions, [:'tlsv1.2']}]` i.e. `Dnsimple.Identity.whoami(client, ssl: [{:versions, [:'tlsv1.2']}])`

It might be good to document that workaround or make that a default option when using the sandbox url.

Thanks!
Adam

**Comment by weppos** [comment]
Thanks for reporting it Adam. We actually use trusted certificates for all our public environments, hence this error is quite surprising.

We are investigating.

**Comment by jacegu** [comment]
@adamkittelson thanks for reporting this. We are investigating this and will fix it as soon as possible. 

Since this is not really related specifically to our Elixir API client we are going to close this issue. We will make sure to ping you here to notify you that the problem has been resolved. Thanks again!

**Comment by jodosha** [comment]
@adamkittelson Which version of OpenSSL do you use? Do you enforce somehow TLSv1.3 or a different version?

Here's the Sandbox certificate:

```shell
$ openssl s_client -connect sandbox.dnsimple.com:443 -servername sandbox.dnsimple.com
CONNECTED(00000003)
depth=3 C = SE, O = AddTrust AB, OU = AddTrust External TTP Network, CN = AddTrust External CA Root
verify return:1
depth=2 C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust RSA Certification Authority
verify return:1
depth=1 C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Domain Validation Secure Server CA
verify return:1
depth=0 OU = Domain Control Validated, OU = EssentialSSL Wildcard, CN = *.sandbox.dnsimple.com
verify return:1
---
Certificate chain
 0 s:/OU=Domain Control Validated/OU=EssentialSSL Wildcard/CN=*.sandbox.dnsimple.com
   i:/C=GB/ST=Greater Manchester/L=Salford/O=Sectigo Limited/CN=Sectigo RSA Domain Validation Secure Server CA
 1 s:/C=US/ST=New Jersey/L=Jersey City/O=The USERTRUST Network/CN=USERTrust RSA Certification Authority
   i:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root
 2 s:/C=GB/ST=Greater Manchester/L=Salford/O=Sectigo Limited/CN=Sectigo RSA Domain Validation Secure Server CA
   i:/C=US/ST=New Jersey/L=Jersey City/O=The USERTRUST Network/CN=USERTrust RSA Certification Authority
 3 s:/C=GB/ST=Greater Manchester/L=Salford/O=Sectigo Limited/CN=Sectigo RSA Domain Validation Secure Server CA
   i:/C=US/ST=New Jersey/L=Jersey City/O=The USERTRUST Network/CN=USERTrust RSA Certification Authority
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIGFDCCBPygAwIBAgIQW6W/NTGgkmTfceb+72ggfTANBgkqhkiG9w0BAQsFADCB
jzELMAkGA1UEBhMCR0IxGzAZBgNVBAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4G
A1UEBxMHU2FsZm9yZDEYMBYGA1UEChMPU2VjdGlnbyBMaW1pdGVkMTcwNQYDVQQD
Ey5TZWN0aWdvIFJTQSBEb21haW4gVmFsaWRhdGlvbiBTZWN1cmUgU2VydmVyIENB
MB4XDTE5MDMxNTAwMDAwMFoXDTIwMDQxMzIzNTk1OVowZDEhMB8GA1UECxMYRG9t
YWluIENvbnRyb2wgVmFsaWRhdGVkMR4wHAYDVQQLExVFc3NlbnRpYWxTU0wgV2ls
ZGNhcmQxHzAdBgNVBAMMFiouc2FuZGJveC5kbnNpbXBsZS5jb20wggEiMA0GCSqG
SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDR8IrnnhlAGKnukSL6c1QCxHuh4/sk2DZM
eDdyvxlfikao/3r+N8yANYOhkQJvmPHE8nrmtobw3k/xZTV7b6kx2o5LvSFs6PAc
t8xP+R0X8FcTpdd4i6jVgQju1FAi1b7RABaa6GZtHs9JHsX0Mu7e3MjwkAki5NM1
NKDaR8ctmJZjSeiAFomsmlIPMafZs9q04MR+PBcIKIKEIKgOtzdswiSmWU5SYJQJ
IIH2Pc/xQHrCRaUba/JwiyoLSk0oJjj++ef5rqW6aJCqIdMgA7wMQ5NpjGskiD0H
3u9k1b1mOBPOv7Fqc6SMLTjCgKnwkNapnPTlLulERThjD/vcLTcVAgMBAAGjggKU
MIICkDAfBgNVHSMEGDAWgBSNjF7EVK2K4Xfpm/mbBeG4AY1h4TAdBgNVHQ4EFgQU
p9/0LbJrb9lRl2u0tDKuQViNBi4wDgYDVR0PAQH/BAQDAgWgMAwGA1UdEwEB/wQC
MAAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMEkGA1UdIARCMEAwNAYL
KwYBBAGyMQECAgcwJTAjBggrBgEFBQcCARYXaHR0cHM6Ly9zZWN0aWdvLmNvbS9D
UFMwCAYGZ4EMAQIBMIGEBggrBgEFBQcBAQR4MHYwTwYIKwYBBQUHMAKGQ2h0dHA6
Ly9jcnQuc2VjdGlnby5jb20vU2VjdGlnb1JTQURvbWFpblZhbGlkYXRpb25TZWN1
cmVTZXJ2ZXJDQS5jcnQwIwYIKwYBBQUHMAGGF2h0dHA6Ly9vY3NwLnNlY3RpZ28u
Y29tMDcGA1UdEQQwMC6CFiouc2FuZGJveC5kbnNpbXBsZS5jb22CFHNhbmRib3gu
ZG5zaW1wbGUuY29tMIIBBAYKKwYBBAHWeQIEAgSB9QSB8gDwAHYAu9nfvB+KcbWT
lCOXqpJ7RzhXlQqrUugakJZkNo4e0YUAAAFpg8QvTwAABAMARzBFAiAzNxLa2/a+
VPdZEXeWvH1FX8Qo39QfJdhMz2oumNqyfQIhANgyFj6nbnfqwSpq/0Th/5THYrE1
wpJWBO7qittO0PuOAHYAXqdz+d9WwOe1Nkh90EngMnqRmgyEoRIShBh1loFxRVgA
AAFpg8QvzAAABAMARzBFAiEAk3iB4y6fOftZ/D8w93+QVVbrXLZaLjMEHZURdGCz
Te4CIAf34tcYEk4+JEEuLEoJ567Dfg3pIaQI8seVJhWwrpFqMA0GCSqGSIb3DQEB
CwUAA4IBAQCPJKyNHay8haAVlFWH01lN0qfbDGyTZ9oVpE2IlR+uBV2DkOVuyhjl
aC12n+wL4U65PwSBYQYuLdCePwT38ym5eQqM86OaEjfyOAaaMblr9YWzuKmE3UKn
00eOnJw5lpICu7l3n+JuCE37TBSPVZs0pkU35hTqH4kg8oa0XvVz9bJevWWfSB3I
s/ftIComCPOJrHoC/HKGzbB1gqCcOL88EYj2NbP2gonA1LmqM4+XnNsN/d4Vh+DA
3YHc9lQsQMC39UgfAK8EtqQX4/yP8dY7Rlu0c0LdGUREbz15KbPTc3dbXhrhNU/o
XUrs3dmDboP8YzeGPmSpuTv6mSDliDun
-----END CERTIFICATE-----
subject=/OU=Domain Control Validated/OU=EssentialSSL Wildcard/CN=*.sandbox.dnsimple.com
issuer=/C=GB/ST=Greater Manchester/L=Salford/O=Sectigo Limited/CN=Sectigo RSA Domain Validation Secure Server CA
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 6601 bytes and written 462 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 2A602698571DC1B0E6C008083309DB76A750656D06F271D42DA8AF3A3A651CEB
    Session-ID-ctx:
    Master-Key: 7B9B8EAFCA90B32A681B8B7EDB472B4DFA68B043DD78911462A2DDCC89E6853CAC69DA0380091818BEEEE041A49A46AF
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1553853368
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
closed
```

**Comment by martinisoft** [comment]
@adamkittelson We have made a few changes which we think have resolved this issue. Can you please re-test and let us know if this resolves your issue? Feel free to email our support@dnsimple.com address to take the conversation there so we can get this resolved.
